# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('like', models.IntegerField(blank=True, null=True)),
                ('scan_times', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('id_user', models.ForeignKey(blank=True, db_column='id_User', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bundle',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('id_bundle', models.ForeignKey(blank=True, db_column='id_Bundle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.Bundle')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CommentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment_location',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bundle', models.ForeignKey(blank=True, db_column='id_Bundle', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.Bundle')),
            ],
            options={
                'db_table': 'scan',
            },
        ),
        migrations.CreateModel(
            name='ScanLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scan_location',
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='id_scan_location',
            field=models.ForeignKey(blank=True, db_column='id_Scan_Location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.ScanLocation'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_comment_location',
            field=models.ForeignKey(blank=True, db_column='id_Comment_Location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.CommentLocation'),
        ),
    ]
